[package]
name = "tilecover"
version = "3.0.0"
edition = "2024"
authors = ["ingalls <ingalls@protonmail.com>"]
description = "Generate the minimum number of tiles to cover a geometry"

homepage = "https://github.com/ingalls/tilecover-rs"
repository = "https://github.com/ingalls/tilecover-rs"

readme = "README.md"

categories = ["algorithms"]
license = "MIT"

[dependencies]
geo-types = "^0.7"
